[package]
name = "snarkos-utilities"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Utilities for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-derives = { path = "../derives", version = "1.1.4", optional = true }
snarkos-errors = { path = "../errors", version = "1.1.4", default-features = false }

bincode = { version = "1.3.1" }
rand = { version = "0.7", default-features = false }

[dev-dependencies]
rand_xorshift = { version = "0.2", default-features = false }

[features]
default = ["std", "derive"]
std = []
derive = ["snarkos-derives"]
