[package]
name = "snarkos-network"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Network for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }
snarkvm-dpc = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }
snarkvm-errors = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }
snarkvm-models = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }
snarkvm-objects = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }
snarkvm-utilities = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "a7e017b", version = "0.0.2" }

snarkos-consensus = { path = "../consensus", version = "1.1.4" }
snarkos-metrics = { path = "../metrics", version = "1.1.4"}
snarkos-storage = { path = "../storage", version = "1.1.4"}

anyhow = { version = "1.0" }
bincode = { version = "1.3.1" }
byteorder = { version = "1" }
capnp = { version = "0.14" }
capnpc = { version = "0.14" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
log = { version = "0.4.11" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7.3" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }
tokio = { version = "0.3", features = ["full"] }
tracing = { default-features = false, features = ["log"], version = "0.1" }
tracing-futures = { version = "0.2" }

[dev-dependencies]
snarkos-testing = { path = "../testing" }

serial_test = { version = "0.5.1" }
tokio-test = { version = "0.2.0" }
tracing-subscriber = { version = "0.2" }

[build-dependencies]
rustc_version = "0.2"
