global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090'] # Only works on Docker Desktop for Windows

  - job_name: 'service-collector'
    static_configs:
      - targets: ['192.168.65.1:8080']
