[package]
name = "snarkos-benchmarks"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Benchmarks for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[[bench]]
name = "network"
path = "network/network.rs"
harness = false

[[bench]]
name = "posw"
path = "posw/posw.rs"
harness = false

[dev-dependencies]
snarkvm-curves = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-marlin = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-models = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-utilities = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }

snarkos-profiler = { path = "../profiler", version = "1.1.4" }
snarkos-posw = { path = "../posw", version = "1.1.4", features = ["test-helpers"] }
snarkos-network = { path = "../network" }
snarkos-testing = { path = "../testing" }

csv = { version = "1" }
derivative = { version = "2" }
digest = { version = "0.7" }
rand = { version = "0.7" }
rayon = { version = "1" }
smallvec = { version = "1.6" }
criterion = { version = "0.3.4", features = ["async_tokio"] }
rand_xorshift = { version = "0.2" }
tokio = { version = "1", features = ["full"] }
